services:

  db:
    image: postgres:16
    container_name: library-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 120307
      POSTGRES_DB: library_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d library_db"]
      interval: 10s
      timeout: 5s
      retries: 5


  api:
    build: .
    container_name: library-api

    env_file:
      - .env

    ports:
      - "5000:5000"

    depends_on:
      db:
        condition: service_healthy


volumes:
  postgres_data: